Update prerelease/final releasenotes
vaadin/platform pull request #1628
Opened 2020-11-06 07:39 UTC by ZheSun88

2020-11-06 10:07 UTC, manolo requested changes
Change second Components section with the changes done in 18.0.0.beta1:
```
### Components
#### Vaadin Flow Components
All listed components' Java integration follow the Vaadin version (v18.0.0.beta1)

#### Vaadin Web Components
```

Add also the following section at the end

```
### Migrating from Vaadin 17
Update the Vaadin version in the build files, and check if the project is using any of the breaking changes mentioned in the 'New and Noteworthy' section above.
In addition, in the case of using the now deprecated PolymerTemplate in views, we encourage to migrate to LitTemplate.
```

2020-11-06 10:37 UTC, ZheSun88 reviewed
done

> *[Reviewable](https://reviewable.io/reviews/vaadin/platform/1628#-:-MLS7Qmr8lXv-Q3GD45s:b-rnrbll)* status: 0 of 2 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-06 16:38 UTC, manolo approved these changes

2020-11-09 10:05 UTC, ZheSun88 reviewed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/platform/1628)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-09 10:05 UTC, merged