chore: add map component to platform
vaadin/platform pull request #2726
Opened 2022-02-08 15:01 UTC by sissbruecker

## Description

Adds the map component to the platform.

2022-02-08 19:56 UTC, ZheSun88 commented
I added the `vaadin-map` entry to **versions.json** too.. this is because we are still using the older way in platform for vaadin-component. 

have talked with Serhii about this, and we will probably remove it in later V23 minors. 


also, i guess the build will fail on the test coverage as this component has not been added to the test classes. let us see.

2022-02-09 07:34 UTC, ZheSun88 commented
I will fix the test for this PR. 

but i think we will not merge it before upgrading the project to V23.1-SNAPSHOT. As this feature is not part of 23.0, adding it to the vaadin-bom will make it totally public to the end users. 

if you need to use this compoment, you will still need to manually add the related dependency to your project.

2022-02-09 09:13 UTC, Artur- commented
Why is this feature flagged component not part of 23? That would make it harder to get any feedback on it before removing the flag

2022-02-09 09:52 UTC, jouni commented
Came here to say the same as Artur, that we want this in 23.0. This is different from how we’ve used to do things, but that’s changing, that experimental features / feature previews can be part of any platform release.

2022-02-10 07:49 UTC, manolo requested changes

2022-02-10 07:49 UTC, manolo commented on vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java
> +        com.vaadin.flow.component.map.Map mapComponent = new com.vaadin.flow.component.map.Map();
We should not have smoke tests for experimental components in the platform until they go to production

2022-02-10 07:49 UTC, manolo commented on vaadin-platform-test/src/main/resources/vaadin-featureflags.properties
> +com.vaadin.experimental.mapComponent=true
I'm doing some modifications in flow so as we don't need to enable experimental components in our test suite.
Blocking this for now

2022-02-11 07:03 UTC, manolo commented on vaadin-platform-test/src/main/resources/vaadin-featureflags.properties
> +com.vaadin.experimental.mapComponent=true
ok lets merge this, and fix flow later

2022-02-11 07:05 UTC, manolo approved these changes

2022-02-11 07:39 UTC, merged