Added project for Vaadin core SBOM checks
vaadin/platform pull request #7001
Opened 2024-11-14 12:45 UTC by edler-san

Run via `./scripts/checkCoreLicenses` from the root folder.

2024-11-14 12:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/platform?pullRequest=7001) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/platform?pullRequest=7001) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/platform?pullRequest=7001) it.</sub>

2024-11-14 16:01 UTC, manolo requested changes

2024-11-14 16:01 UTC, manolo commented on scripts/data/approved-licenses.txt
> +0BSD
With this approach, we need to maintain twice this list

2024-11-14 16:01 UTC, manolo commented on scripts/checkCoreLicenses.sh
> +#!/usr/bin/env bash
The solution works fine so the procedure is good, but I think it's worth to re-factor

2024-11-19 16:53 UTC, edler-san commented on vaadin-core-sbom/pom.xml
> +        <!-- <dependency>
done

2024-11-19 16:53 UTC, edler-san commented on vaadin-core-sbom/pom.xml
> +    <profiles>
done

2024-11-19 16:54 UTC, edler-san commented on scripts/checkCoreLicenses.sh
> +mvn -ntp -B org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom -q -T 1C
I managed to use the existing functionality - since it also assumed the cyclone-generated JSON file that worked nicely.

2024-11-20 06:34 UTC, manolo requested changes

2024-11-20 06:34 UTC, manolo commented on scripts/generateAndCheckSBOM.js
> +const coreProject = path.resolve('vaadin-core-sbom');
you are not using this var

2024-11-20 06:34 UTC, manolo commented on scripts/generateAndCheckSBOM.js
> +    await run('mvn -ntp -B org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom -q -f ../vaadin-core-sbom');
shouldn't you use coreProject var here?

2024-11-20 06:34 UTC, manolo commented on vaadin-core-sbom/pom.xml
> +<project xmlns="http://maven.apache.org/POM/4.0.0"
add this module to the sbom profile in parent pom.xml

2024-11-20 14:44 UTC, edler-san commented on scripts/generateAndCheckSBOM.js
> +const coreProject = path.resolve('vaadin-core-sbom');
Updated

2024-11-20 14:44 UTC, edler-san commented on scripts/generateAndCheckSBOM.js
> +    await run('mvn -ntp -B org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom -q -f ../vaadin-core-sbom');
yep

2024-11-26 11:52 UTC, merged